### ISSUE TITLE
Downsample / concatenate?

### ISSUE THREAD

**Issue by biggzlar** [epfml/attention-cnn#5]
Any explanation as to why this function is so involved? It's simply copying the input tensor and reshaping it. Why do we need four steps to do this? 

https://github.com/epfml/attention-cnn/blob/21483bba7d8e3ff1dc104c1b311a44a84d5c9db4/models/transformer.py#L145

**Comment by jbcdnr** [comment]
I think the reshaping is not just one line because vertical neighboring pixels are not next to each other in memory. So for example for a 2x2 concatenation, we first concatenate the channels of the horizontal neighbors. Then permute the dimensions and concatenate the vertical neighbors that are contiguous in memory. I was a bit crazy with the `.contiguous()`, some are maybe not necessary but they would lead to a no op so should not be a problem ;)

I am curious if you have a better/simpler solution that passes a test to match the output of my function.

**Comment by jbcdnr** [comment]
It could be made simpler using [unfold](https://pytorch.org/docs/master/generated/torch.nn.Unfold.html#unfold) probably.
